export enum NAVBAR_STATE_TYPE {
    LISTING_PAGES = "LISTING_PAGES",
    PROJECTS_OVERVIEW = "PROJECTS_OVERVIEW", 
    QUICK_ACCESS = "QUICK_ACCESS",
    HELP = "HELP",
    USER_VIEW = "USER_VIEW",
    NOTIFICATIONS="NOTIFICATIONS",
    LANG="LANG",
    DEFAULT = "DEFAULT",

}
